config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'dashboard' => 'home#dashboard'

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  devise_scope :user do
    get '/api/current_user' => 'users/sessions#show_current_user'
  end

  resource :profile, controller: :profile, except: [:destroy]

  resources :clients
  resources :jobs do
    resources :invoices
  end

  resources :entries

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :clients
      resources :jobs do
        resources :invoices
      end
      resources :entries
    end
  end

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  enum status: ["unattached", "finished", "attached"]

  belongs_to :user
  belongs_to :invoice
  belongs_to :topic

  monetize :subtotal_cents, allow_nil: true

  validates :user_id, :entry_date, :start_time, :invoice_id, presence: true

  after_update :check_end_time # This is the ajax approach where begin and end times are logged in separate posts
  #after_create :check_end_time # This version works for a single http request with begin & end times

  def check_end_time
    return unless self.end_time?
    calculate_total_time unless self.total_time?
  end

  def calculate_total_time
    self.total_time = convert_to_hours(self.end_time - self.start_time)
    calculate_subtotal
    self.finished!
  end

  def convert_to_hours(seconds)
    (seconds.to_d / 3600)
  end

  def calculate_subtotal
    rate = self.invoice.job.rate
    self.subtotal = Money.new(self.total_time * rate)
  end

  # Figure out how to override the finished! enum method
  # def finished!
  #   if self.end_time?
  #     super
  #   else
  #     raise
  #   end
  # end
end

app/controllers/api/v1/entries_controller.rb
module Api
  module V1
    class EntriesController < ApplicationController
      before_action :set_entry, only: [:show, :edit, :update, :destroy]
      before_action :authenticate_user!

      def index
        @entries = current_user.entries
        render json: @entries
      end

      def show
        render json: @entry
      end

      def new
        @entry = Entry.new
      end

      def edit
      end

      def create
        @entry = current_user.entries.new(entry_params)

        if @entry.save
          render json: @entry, status: :created, location: @entry
        else
          render json: @entry.errors, status: :unprocessable_entity
        end
      end

      def update
        if @entry.update(entry_params)
          head :no_content
        else
          render json: @entry.errors, status: :unprocessable_entity
        end
      end

      def destroy
        @entry.destroy
        head :no_content
      end

      private

        def set_entry
          @entry = current_user.entries.find(params[:id])
        end

        def entry_params(params)
          params.require(:entry).permit(
            :entry_date, :start_time, :end_time,
            :total_time, :status, :user_id, 
            :invoice_id, :topic_id)
        end

    end
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry_statuses
  before_action :set_entry, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @entries = current_user.entries
  end

  def show
  end

  def new
    @entry = Entry.new
    @entry.user_id = current_user.id
  end

  def edit
  end

  def create
    params = entry_params
    @entry = current_user.entries.new(entry_params)
    @entry.start_time = Time.at(params[:start_time].to_i)
    @entry.end_time = Time.at(params[:end_time].to_i)
    @entry.entry_date = Time.at(params[:entry_date].to_i)

    if @entry.save
      redirect_to entries_path, notice: "Entry successfully created."
    else
      render :new, alert: "There was a problem creating your entry. Please try again."
    end
  end

  def update
    if @entry.update(entry_params)
      redirect_to @entry, notice: "Entry successfully updated."
    else
      render :edit, alert: "There was a problem updating your entry. Please try again."
    end
  end

  def destroy
    if @entry.destroy
      redirect_to entries_path, notice: "Entry has been deleted."
    else
      redirect_to @entry, alert: "There was a problem deleting your entry. Please try again."
    end
  end

  private

    def set_entry
      @entry = Entry.find(params[:id])
    end

    def set_entry_statuses
      @statuses = Entry.statuses
    end

    def entry_params
      params.require(:entry).permit(:entry_date, :start_time, :end_time, :total_time, :status, :user_id, :invoice_id, :topic_id )
    end

end

app/helpers/entries_helper.rb
module EntriesHelper
  def format_time(time)
    time.localtime.strftime("%r")
  end
end

app/views/entries/_entry_form.html.erb
<%= bootstrap_form_for @entry, layout: :horizontal, label_col: "col-xs-3", control_col: "col-xs-9" do |form| %>
  <%= form.date_field :entry_date %>
  <%= form.time_field :start_time %>
  <%= form.time_field :end_time %>
  <%#= form.select :status, options_for_select(@statuses.map {|s| [s[0].humanize, s[0]] }, selected: @entry.status) if params[:action] == "edit" %>
  <%= form.collection_select :invoice, current_user.invoices, :id, :invoice_date, html: { include_blank: true, selected: @entry.invoice } %>
  <%= form.text_field :topic_id %>
  <%= form.button "Save entry", class: "btn btn-primary", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Saving..."} %>
<% end %>

app/views/entries/edit.html.erb
<div class="page-header">
  <h1>Edit entry</h1>
  
  <%= link_to "Back to entry", entry_path(@entry), class: "btn btn-default btn-sm" %>
</div>

<%= render 'entry_form' %>

app/views/entries/index.html.erb
<div class="page-header">
  <h1>Entry list<br/>
  <small>All your timetracker entries.</small></h1>
  
  <%= link_to "Add a new entry", new_entry_path, class: "btn btn-primary" %>
</div>

<table class="table table-striped table-hover">
  <thead>
    <th>Entry date</th>
    <th>Start time</th>
    <th>End time</th>
    <th>Total time</th>
    <th>Status</th>
    <th>Client / Job</th>
    <th>Invoice date</th>
    <th>Topic</th>
    <th></th>
  </thead>
  <tbody>
    <% @entries.each do |entry| %>
      <tr>
        <td><%= entry.entry_date.to_formatted_s(:long) %></td>
        <td><%= format_time entry.start_time %></td>
        <td><%= format_time entry.end_time %></td>
        <td><%= entry.total_time %></td>
        <td><%= entry.status %></td>
        <td><%= entry.invoice.job.client.company %> / <%= entry.invoice.job.job_name %></td>
        <td><%= entry.invoice.invoice_date.to_formatted_s(:long) %></td>
        <td><%= entry.topic.name if entry.topic %></td>
        <td>
          <%= link_to '<span class="glyphicon glyphicon-edit"></span> Edit'.html_safe, edit_entry_path(entry), class: "btn btn-primary btn-sm" %>
          <%= link_to "View", entry_path(entry), class: "btn btn-primary btn-sm" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/entries/new.html.erb
<div class="page-header">
  <h1>New entry<br/>
  <small>Start tracking your time.</small></h1>
  
  <%= link_to "Back to all entries", entries_path, class: "btn btn-default btn-sm" %>
</div>

<div>
  <h2 class="text-center">Start tracking time now</h2>
  <br>
  <div class="btn-group btn-group-justified">
    <div class="btn-group">
      <button type="button" class="btn btn-success btn-lg start-button">Start</button>
    </div>
    <div class="btn-group">
      <button type="button" class="btn btn-danger btn-lg stop-button">Stop</button>
    </div>
  </div>
  <div id="record" class="panel panel-default">
    <div class="panel-body">
      <p class="timer text-center active"></p>
    </div>
  </div>
</div>


<%= bootstrap_form_for @entry do |form| %>
  <%= form.hidden_field :user_id %>
  <%= form.hidden_field :entry_date %>
  <%= form.hidden_field :start_time %>
  <%= form.hidden_field :end_time %>
  <%= form.select :invoice_id, options_for_select(Invoice.invoices_for current_user), label: "Choose an invoice for this entry", include_blank: true %>
  <%#= form.select :topic_id, options_for_select(Topic.all), label: "Choose a topic", include_blank: true %>
  <%= form.text_field :topic_id %>
  <%= form.button "Save entry", class: "btn btn-primary", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Saving..."} %>
<% end %>

app/views/entries/show.html.erb
<div class="page-header">
  <h1>Entry for <%= @entry.entry_date.to_formatted_s(:long) %><br/>
    <small>Total time: <%= @entry.total_time? ? @entry.total_time : "0" %> hours</small></h1>
  
  <%= link_to "Edit entry", edit_entry_path(@entry), class: "btn btn-primary" %>
  <%= link_to "All entries", entries_path, class: "btn btn-primary" %>
</div>

<div class="row">
  <div class="col-xs-4 col-xs-offset-1">
    <h3 class="text-right">Start time:</h3>
    <h3 class="text-right">End time:</h3>
    <h3 class="text-right">Subtotal:</h3>
    <h3 class="text-right">Status:</h3>
    <h3 class="text-right">Topic:</h3>
  </div>

  <div class="col-xs-6">
    <h3><%= format_time @entry.start_time %>&nbsp;</h3>
    <h3><%= format_time @entry.end_time %>&nbsp;</h3>
    <h3><%= humanized_money_with_symbol @entry.subtotal %>&nbsp;</h3>
    <h3><%= @entry.status %>&nbsp;</h3>
    <h3><%= @entry.topic.name %>&nbsp;</h3>
  </div>
</div> <!-- row -->