config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'dashboard' => 'home#dashboard'

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  devise_scope :user do
    get '/api/current_user' => 'users/sessions#show_current_user'
  end

  resource :profile, controller: :profile, except: [:destroy]

  resources :clients
  resources :jobs do
    resources :invoices
  end

  resources :entries

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :clients
      resources :jobs do
        resources :invoices
      end
      resources :entries
    end
  end

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  enum status: [:active, :submitted, :paid]

  belongs_to :job
  has_many :entries

  validates :invoice_date, :status, presence: true

  monetize :total_cents

  def self.invoices_for(current_user)
    current_user.invoices.map { |i| ["#{i.job.job_name}: #{i.invoice_date}", i.id]  }
  end
end

app/controllers/api/v1/invoices_controller.rb
module Api
  module V1
    class InvoicesController < ApplicationController
      before_action :set_invoice, only: [:show, :edit, :update]
      before_action :authenticate_user!

      def index
        @job = current_user.jobs.find(params[:job_id])
        @invoices = @job.invoices
        render json: @invoices
      end

      def show
        render json: @invoice
      end

      def new
        @job = current_user.jobs.find(params[:job_id])
        @invoice = Invoice.new
      end

      def edit
      end

      def create
        @job = current_user.jobs.find(params[:job_id])
        @invoice = @job.invoices.new(invoice_params)

        if @invoice.save
          render json: @invoice, status: :created, location: @invoice
        else
          render json: @invoice.errors, status: :unprocessable_entity
        end
      end

      def update
        if @invoice.update(invoice_params)
          head :no_content
        else
          render json: @invoice.errors, status: :unprocessable_entity
        end
      end

      private

        def set_invoice
          @job = current_user.jobs.find(params[:job_id])
          @invoice = @job.invoices.find(params[:id])
        end

        def invoice_params(params)
          params.require(:invoice).permit(
            :invoice_date, :status, :job_id, :total)
        end

    end
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]
  before_action :set_invoice_statuses, only: [:new, :edit]
  before_action :authenticate_user!

  def index
    @job = current_user.jobs.find(params[:job_id])
    @invoices = @job.invoices
  end

  def show
  end

  def new
    @job = current_user.jobs.find(params[:job_id])
    # @invoice = @job.invoices.new
    @invoice = Invoice.new
  end

  def edit
  end

  def create
    @job = current_user.jobs.find(params[:job_id])
    # @invoice = @job.invoices.create(params(invoice_params))
    @invoice = @job.invoices.new(invoice_params)

    if @invoice.save
      redirect_to job_invoices_path, notice: "Invoice successfully created."
    else
      render action: 'new', alert: "There was a problem creating your invoice. Please try again."
    end
  end

  def update
    # @statuses = Invoice.statuses

    if @invoice.update(invoice_params)
      redirect_to job_invoice_path(@job, @invoice), notice: "Invoice successfully updated."
    else
      render action: 'edit', alert: "There was a problem updating your invoice. Please try again."
    end
  end

  def destroy
    if @invoice.destroy
      redirect_to job_invoices_path, notice: "Invoice has been deleted."
    else
      redirect_to @invoice, alert: "There was a problem deleting your invoice. Please try again."
    end
  end

  private

    def set_invoice
      @job = current_user.jobs.find(params[:job_id])
      @invoice = @job.invoices.find(params[:id])
    end

    def set_invoice_statuses
    @statuses = Invoice.statuses
    end

    def invoice_params
      params.require(:invoice).permit(:invoice_date, :status, :job_id)
    end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_invoice_form.html.erb
<%= bootstrap_form_for [@job, @invoice], layout: :horizontal, label_col: "col-xs-3", control_col: "col-xs-9" do |form| %>
  <%= form.date_field :invoice_date %>
  <%= form.select :status, options_for_select(@statuses.map {|s| [s[0].humanize, s[0]] }, selected: @invoice.status) if params[:action] == "edit" %>
  <%= form.button "Save invoice", class: "btn btn-primary", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Saving..."} %>
<% end %>

app/views/invoices/edit.html.erb
<div class="page-header">
  <h1>Edit invoice</h1>
  
  <%= link_to "Cancel", job_invoice_path(@job, @invoice), class: "btn btn-default btn-sm" %>
</div>

<%= render 'invoice_form' %>

app/views/invoices/index.html.erb
<div class="page-header">
  <h1>Invoices<br/>
  <small>All your invoices for <%= @job.job_name %>.</small></h1>
  
  <%= link_to "Add an invoice", new_job_invoice_path(@job), class: "btn btn-primary" %>
</div>

<table class="table table-striped table-hover">
  <thead>
    <th>Invoice date</th>
    <th>Status</th>
    <th></th>
  </thead>
  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= invoice.invoice_date.to_formatted_s(:long) %></td>
        <td><%= invoice.status %></td>
        <td>
          <%= link_to '<span class="glyphicon glyphicon-edit"></span> Edit'.html_safe, edit_job_invoice_path(@job, invoice), class: "btn btn-primary btn-sm" %>
          <%= link_to "View", job_invoice_path(@job, invoice), class: "btn btn-primary btn-sm" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/invoices/new.html.erb
<div class="page-header">
  <h1>New invoice<br/>
  <small>Add an invoice to <%= @job.job_name %>.</small></h1>
  
  <%= link_to "Back to invoice list", job_invoices_path(@job), class: "btn btn-default btn-sm" %>
</div>

<%= render 'invoice_form' %>

app/views/invoices/show.html.erb
<div class="page-header">
  <h1>Invoice for <%= @invoice.invoice_date.to_formatted_s(:long) %><br/>
    <small><%= @job.job_name %></small></h1>
  
  <%= link_to "Edit invoice", edit_job_invoice_path(@job, @invoice), class: "btn btn-primary" %>
  <%= link_to "All invoices", job_invoices_path(@job), class: "btn btn-primary" %>
</div>

<table class="table table-striped table-hover">
  <thead>
    <th>Entry date</th>
    <th>Start time</th>
    <th>End time</th>
    <th>Total time</th>
    <th>Subtotal</th>
    <th></th>
  </thead>
  <tbody>
    <% @invoice.entries.each do |entry| %>
      <tr>
        <td><%= entry.entry_date.to_formatted_s(:long) %></td>
        <td><%= format_time entry.start_time %></td>
        <td><%= format_time entry.end_time %></td>
        <td><%= entry.total_time %></td>
        <td><%= entry.subtotal %></td>
        <td>
          <%#= link_to '<span class="glyphicon glyphicon-edit"></span> Edit'.html_safe, edit_job_invoice_path(@job, @invoice), class: "btn btn-primary btn-sm" %>
          <%= link_to "View", entry_path(entry), class: "btn btn-primary btn-sm" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>