config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'dashboard' => 'home#dashboard'

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  devise_scope :user do
    get '/api/current_user' => 'users/sessions#show_current_user'
  end

  resource :profile, controller: :profile, except: [:destroy]

  resources :clients
  resources :jobs do
    resources :invoices
  end

  resources :entries

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :clients
      resources :jobs do
        resources :invoices
      end
      resources :entries
    end
  end

end

app/models/job.rb
class Job < ActiveRecord::Base
  include Filterable

  belongs_to :client
  has_many :invoices
  has_many :entries, through: :invoices

  monetize :rate_cents

  validates :job_name, :start_date, :end_date, :rate, presence: true
  validate :end_date_cannot_be_in_the_past, on: :create

  scope :client, -> (client_id) { where client_id: client_id }

  private

    def end_date_cannot_be_in_the_past
      if end_date.present? && end_date < Date.today
        errors.add :end_date, "can't be in the past"
      end
    end
end

app/controllers/api/v1/jobs_controller.rb
module Api
  module V1
    class JobsController < ApplicationController
      before_action :set_job, only: [:show, :edit, :update]
      before_action :authenticate_user!

      def index
        @jobs = current_user.jobs
        render json: @jobs
      end

      def show
        render json: @job
      end

      def new
        @job = Job.new
      end

      def edit
      end

      def create
        @job = current_user.jobs.new(job_params)

        if @job.save
          render json: @job, status: :created, location: @job
        else
          render json: @job.errors, status: :unprocessable_entity
        end
      end

      def update
        if @job.update(job_params)
          head :no_content
        else
          render json: @job.errors, status: :unprocessable_entity
        end
      end

      private

        def set_job
          @job = current_user.jobs.find(params[:id])
        end

        def job_params(params)
          params.require(:job).permit(
            :job_name, :start_date, :end_date, :client_id, :rate)
        end

    end
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  def index
    @jobs = current_user.jobs
    @jobs = Job.filter(params.slice(:client))
  end

  def show
  end

  def new
    @job = Job.new
  end

  def edit
  end

  def create
    @job = current_user.jobs.new(job_params)

    if @job.save
      redirect_to jobs_path, notice: "Job successfully created."
    else
      render action: 'new', alert: "There was a problem creating your job. Please try again."
    end
  end

  def update
    if @job.update(job_params)
      redirect_to @job, notice: "Job successfully updated."
    else
      render action: 'edit', alert: "There was a problem updating your job."
    end
  end

  def destroy
    if @job.destroy
      redirect_to jobs_path, notice: "Your job has been deleted."
    else
      redirect_to @job, alert: "There was a problem deleting your job. Please try again."
    end
  end

  private

    def set_job
      @job = current_user.jobs.find(params[:id])
    end

    def job_params
      params.require(:job).permit(:job_name, :start_date, :end_date, :rate, :client_id)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_job_form.html.erb
<%= bootstrap_form_for @job, layout: :horizontal, label_col: "col-xs-3", control_col: "col-xs-9" do |form| %>
  <%= form.text_field :job_name %>
  <%= form.date_field :start_date %>
  <%= form.date_field :end_date %>
  <%= form.number_field :rate %>
  <%= form.collection_select :client_id, current_user.clients, :id, :company %>
  <%= form.button "Save job", class: "btn btn-primary", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Saving..."} %>
<% end %>

app/views/jobs/edit.html.erb
<div class="page-header">
  <h1>Edit job</h1>
  
  <%= link_to "Back to job", job_path(@job), class: "btn btn-default btn-sm" %>
  <%= link_to "Back to job list", jobs_path, class: "btn btn-default btn-sm" %>
</div>

<%= render 'job_form' %>

app/views/jobs/index.html.erb
<div class="page-header">
  <h1>Job list<br/>
  <small>All your available jobs.</small></h1>
  
  <%= link_to "Add a new job", new_job_path, class: "btn btn-primary" %>
</div>

<table class="table table-striped table-hover">
  <thead>
    <th>Client</th>
    <th>Job</th>
    <th>Start date</th>
    <th>End date</th>
    <th>Rate</th>
    <th></th>
  </thead>
  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.client.company %></td>
        <td><%= job.job_name %></td>
        <td><%= job.start_date.to_date.to_formatted_s(:long) %></td>
        <td><%= job.end_date.to_date.to_formatted_s(:long) %></td>
        <td><%= number_to_currency job.rate %></td>
        <td>
          <%= link_to '<span class="glyphicon glyphicon-edit"></span> Edit'.html_safe, edit_job_path(job), class: "btn btn-primary btn-sm" %>
          <%= link_to "View", job_path(job), class: "btn btn-primary btn-sm" %>
          <%= link_to "Invoices", job_invoices_path(job), class: "btn btn-primary btn-sm" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/jobs/new.html.erb
<div class="page-header">
  <h1>New job<br/>
  <small>Add a job to a client.</small></h1>
  
  <%= link_to "Back to job list", jobs_path, class: "btn btn-default btn-sm" %>
</div>

<%= render 'job_form' %>

app/views/jobs/show.html.erb
<div class="page-header">
  <h1><%= @job.job_name %></h1>
  
  <%= link_to "Edit job", edit_job_path(@job), class: "btn btn-primary" %>
  <%= link_to "All jobs", jobs_path, class: "btn btn-primary" %>
</div>

<div class="row">
  <div class="col-xs-4 col-xs-offset-1">
    <h3 class="text-right">Job name:</h3>
    <h3 class="text-right">Start date:</h3>
    <h3 class="text-right">End date:</h3>
    <h3 class="text-right">Hourly rate:</h3>
    <h3 class="text-right">Client:</h3>
  </div>

  <div class="col-xs-6">
    <h3><%= @job.job_name %></h3>
    <h3><%= @job.start_date.to_date.to_formatted_s(:long) %></h3>
    <h3><%= @job.end_date.to_date.to_formatted_s(:long) %></h3>
    <h3><%= number_to_currency @job.rate %></h3>
    <h3><%= @job.client.company %></h3>
  </div>
</div> <!-- row -->