config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'dashboard' => 'home#dashboard'

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  devise_scope :user do
    get '/api/current_user' => 'users/sessions#show_current_user'
  end

  resource :profile, controller: :profile, except: [:destroy]

  resources :clients
  resources :jobs do
    resources :invoices
  end

  resources :entries

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :clients
      resources :jobs do
        resources :invoices
      end
      resources :entries
    end
  end

end

app/models/client.rb
class Client < ActiveRecord::Base
  belongs_to :user
  has_many :jobs
  has_many :invoices, through: :jobs

  validates :company, :address, :city, presence: true
  validates :zip_code, numericality: { only_integer: true }, length: { is: 5 }
  validates :phone_number, format: { with: /\A\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})\z/, message: "Please enter a valid phone number with area code."}, allow_blank: true
  validates_with StateValidator
end

app/controllers/api/v1/clients_controller.rb
module Api
  module V1
    class ClientsController < ApplicationController
      before_action :set_client, only: [:show, :edit, :update]
      before_action :authenticate_user!

      def index
        @clients = current_user.clients
        render json: @clients

        # render status: 200,
        #   json: {
        #     success: true,
        #     info: "Current user",
        #     clients: @clients
        #   }
      end

      def show
        render json: @client
      end

      def new
        @client = Client.new
      end

      def edit
      end

      def create
        @client = current_user.clients.new(client_params)

        if @client.save
          render json: @client, status: :created, location: @client
        else
          render json: @client.errors, status: :unprocessable_entity
        end
      end

      def update
        if @client.update(client_params)
          head :no_content
        else
          render json: @client.errors, status: :unprocessable_entity
        end
      end

      private

        def set_client
          @client = current_user.clients.find(params[:id])
        end

        def client_params(params)
          params.require(:client).permit(
            :contact_name, :company, :address, :address2, 
            :city, :state, :zip_code, :phone_number)
        end

    end
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @clients = current_user.clients
  end

  def show
  end

  def new
    @client = Client.new
  end

  def edit
  end

  def create
    @client = current_user.clients.new(client_params)

    if @client.save
      redirect_to clients_path, notice: "Client successfully created."
      # redirect_to @client, notice: "Client successfully created."
    else
      render action: 'new', alert: "There was a problem creating your client. Please try again."
    end
  end

  def update
    if @client.update(client_params)
      redirect_to @client, notice: "Client successfully updated."
    else
      render action: 'edit', alert: "There was a problem updating your client. Please try again."
    end
  end

  def destroy
    if @client.destroy
      redirect_to clients_path, notice: "Your client has been deleted."
    else
      redirect_to @client, alert: "There was a problem deleting your client. Please try again."
    end
  end

  private

    def set_client
      @client = current_user.clients.find(params[:id])
    end

    def client_params
      params.require(:client)
        .permit(:contact_name, :company, :address, :address2, 
          :city, :state, :zip_code, :phone_number, :user_id)
    end
end

app/helpers/client_helper.rb
module ClientHelper
end

app/views/clients/_client_form.html.erb
<%= bootstrap_form_for @client, layout: :horizontal, label_col: "col-xs-3", control_col: "col-xs-9" do |form| %>
  <%= form.text_field :contact_name %>
  <%= form.text_field :company %>
  <%= form.text_field :address %>
  <%= form.text_field :address2 %>
  <%= form.text_field :city %>
  <%= form.text_field :state %>
  <%= form.text_field :zip_code %>
  <%= form.text_field :phone_number %>
  <%= form.button "Save client", class: "btn btn-primary", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Saving..."} %>
<% end %>

app/views/clients/edit.html.erb
<div class="page-header">
  <h1>Edit client</h1>
  
  <%= link_to "Back to client", client_path(@client), class: "btn btn-default btn-sm" %>
</div>

<%= render 'client_form' %>

app/views/clients/index.html.erb
<div class="page-header">
  <h1>Client list<br/>
  <small>All your invoicable clients.</small></h1>
  
  <%= link_to "Add a new client", new_client_path, class: "btn btn-primary" %>
</div>

<table class="table table-striped table-hover">
  <thead>
    <th>Company</th>
    <th>Contact</th>
    <th>Address</th>
    <th>Phone number</th>
    <th></th>
  </thead>
  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.company %></td>
        <td><%= client.contact_name %></td>
        <td>
          <address>
            <%= client.address %><br>
            <% unless client.address2.blank? %><%= client.address2 %><br> <% end %>
            <%= client.city %>, <%= client.state %> <%= client.zip_code %><br>
          </address>  
        </td>
        <td><%= client.phone_number %></td>
        <td><%= link_to '<span class="glyphicon glyphicon-edit"></span> Edit'.html_safe, edit_client_path(client), class: "btn btn-primary btn-sm" %>
           
          <%= link_to "Client's jobs", jobs_path(client: client), class: "btn btn-primary btn-sm" %></td>
      </tr>
      <% end %>
  </tbody>
</table>

app/views/clients/new.html.erb
<div class="page-header">
  <h1>New client<br/>
  <small>Add an invoicable client.</small></h1>
  
  <%= link_to "Back to client list", clients_path, class: "btn btn-default btn-sm" %>
</div>

<%= render 'client_form' %>

app/views/clients/show.html.erb
<div class="page-header">
  <h1><%= @client.company %></h1>
  
  <%= link_to "Edit client", edit_client_path(@client), class: "btn btn-primary" %>
  <%= link_to "All clients", clients_path, class: "btn btn-primary" %>
</div>

<!-- REDO AS A TABLE -->

<div class="row">
  <div class="col-xs-4 col-xs-offset-1">
    <h3 class="text-right">Contact name:</h3>
    <h3 class="text-right">Company name:</h3>
    <h3 class="text-right">Address:</h3>
    <h3 class="text-right">Address:</h3>
    <h3 class="text-right">City:</h3>
    <h3 class="text-right">State:</h3>
    <h3 class="text-right">Zip:</h3>
    <h3 class="text-right">Phone:</h3>
  </div>

  <div class="col-xs-6">
    <h3><%= @client.contact_name %>&nbsp;</h3>
    <h3><%= @client.company %>&nbsp;</h3>
    <h3><%= @client.address %>&nbsp;</h3>
    <h3><%= @client.address2 %>&nbsp;</h3>
    <h3><%= @client.city %>&nbsp;</h3>
    <h3><%= @client.state %>&nbsp;</h3>
    <h3><%= @client.zip_code %>&nbsp;</h3>
    <h3><%= @client.phone_number %>&nbsp;</h3>
  </div>
</div> <!-- row -->